# nginx 配置
# （可选，仅在测试纯静态页面时使用）
# （一般不用，因为不含参数验证等功能）
#  - 子路径 /xm 映射到 output/xm
server {
    listen       8767;
    server_name  localhost;

    # 根目录指向 output（不是 output/xm）
    root   "E:/ProgramProjects/VScode_projects/quartz-fullstack/output";
    index  index.html;

    # /xm/ 路径映射到 xm 目录
    location /xm/ {
        # 使用 root 会自动拼接，所以 /xm/ -> output/xm/
        try_files $uri $uri.html $uri/ =404;
    }

    # 可选：404 页面
    error_page  404  /xm/404.html;
}
